library(readr)
#Environmental Variables 

#Environmental Variables 
#Current League Information
current_league_start_date = as.Date("13/03/2020", format = "%d/%m/%Y")
current_league_name = as.character("Delirium")

#Subset items with names 
subset_names = read.csv("./data/subset_names.csv", sep=",", fileEncoding = "latin1")
#League List
league_list = data.frame("League" = c("Essence","Abyss","Harbinger","Legacy","Breach", "Bestiary","Bestiary Flashback","Incursion",
                                      "Incursion Flashback","Delve","Betrayal","Synthesis", "Blight","Legion", "Metamorph"),
                         "LeagueHC"= c("Essence HC","Abyss HC","Harbinger HC","Legacy HC","Breach HC", "Bestiary HC","Bestiary Flashback HC","Incursion HC",
                                       "Incursion Flashback HC","Delve HC","Betrayal HC","Synthesis HC", "Blight HC","Legion HC", "Metamorph HC"))

#Create DB with *.CSV Item Type files
# LSC
BaseType        = read.csv("./data/LSC.BaseType.csv", sep=",", fileEncoding = "latin1")
Essence         = read.csv("./data/LSC.Essence.csv", sep=",", fileEncoding = "latin1")
Map             = read.csv("./data/LSC.Map.csv", sep=",", fileEncoding = "latin1")
Scarab          = read.csv("./data/LSC.Scarab.csv", sep=",", fileEncoding = "latin1")
UniqueFlask     = read.csv("./data/LSC.UniqueFlask.csv", sep=",", fileEncoding = "latin1")
UniqueWeapon    = read.csv("./data/LSC.UniqueWeapon.csv", sep=",", fileEncoding = "latin1")
Beast           = read.csv("./data/LSC.Beast.csv", sep=",", fileEncoding = "latin1")
Fossil          = read.csv("./data/LSC.Fossil.csv", sep=",", fileEncoding = "latin1")
Oil             = read.csv("./data/LSC.Oil.csv", sep=",", fileEncoding = "latin1")
SkillGem        = read.csv("./data/LSC.SkillGem.csv", sep=",", fileEncoding = "latin1")
Vial            = read.csv("./data/LSC.Vial.csv", sep=",", fileEncoding = "latin1")
UniqueJewel     = read.csv("./data/LSC.UniqueJewel.csv", sep=",", fileEncoding = "latin1")
Currency        = read.csv("./data/LSC.Currency.csv", sep=",", fileEncoding = "latin1")
Fragment        = read.csv("./data/LSC.Fragment.csv", sep=",", fileEncoding = "latin1")
Prophecy        = read.csv("./data/LSC.Prophecy.csv", sep=",", fileEncoding = "latin1")
UniqueAccessory = read.csv("./data/LSC.UniqueAccessory.csv", sep=",", fileEncoding = "latin1")
UniqueMap       = read.csv("./data/LSC.UniqueMap.csv", sep=",", fileEncoding = "latin1")
DivinationCard  = read.csv("./data/LSC.DivinationCard.csv", sep=",", fileEncoding = "latin1")
HelmetEnchant   = read.csv("./data/LSC.HelmetEnchant.csv", sep=",", fileEncoding = "latin1")
Resonator       = read.csv("./data/LSC.Resonator.csv", sep=",", fileEncoding = "latin1")
UniqueArmour    = read.csv("./data/LSC.UniqueArmour.csv", sep=",", fileEncoding = "latin1")
Incubator       = read.csv("./data/LSC.Incubator.csv", sep=",", fileEncoding = "latin1")
Watchstone      = read.csv("./data/LSC.Watchstone.csv", sep=",", fileEncoding = "latin1")

# LHC
BaseType_lhc        = read.csv("./data/LHC.BaseType.csv", sep=",", fileEncoding = "latin1")
Essence_lhc         = read.csv("./data/LHC.Essence.csv", sep=",", fileEncoding = "latin1")
Map_lhc             = read.csv("./data/LHC.Map.csv", sep=",", fileEncoding = "latin1")
Scarab_lhc          = read.csv("./data/LHC.Scarab.csv", sep=",", fileEncoding = "latin1")
UniqueFlask_lhc     = read.csv("./data/LHC.UniqueFlask.csv", sep=",", fileEncoding = "latin1")
UniqueWeapon_lhc    = read.csv("./data/LHC.UniqueWeapon.csv", sep=",", fileEncoding = "latin1")
Beast_lhc           = read.csv("./data/LHC.Beast.csv", sep=",", fileEncoding = "latin1")
Fossil_lhc          = read.csv("./data/LHC.Fossil.csv", sep=",", fileEncoding = "latin1")
Oil_lhc             = read.csv("./data/LHC.Oil.csv", sep=",", fileEncoding = "latin1")
SkillGem_lhc        = read.csv("./data/LHC.SkillGem.csv", sep=",", fileEncoding = "latin1")
Vial_lhc            = read.csv("./data/LHC.Vial.csv", sep=",", fileEncoding = "latin1")
UniqueJewel_lhc     = read.csv("./data/LHC.UniqueJewel.csv", sep=",", fileEncoding = "latin1")
Currency_lhc        = read.csv("./data/LHC.Currency.csv", sep=",", fileEncoding = "latin1")
Fragment_lhc        = read.csv("./data/LHC.Fragment.csv", sep=",", fileEncoding = "latin1")
Prophecy_lhc        = read.csv("./data/LHC.Prophecy.csv", sep=",", fileEncoding = "latin1")
UniqueAccessory_lhc = read.csv("./data/LHC.UniqueAccessory.csv", sep=",", fileEncoding = "latin1")
UniqueMap_lhc       = read.csv("./data/LHC.UniqueMap.csv", sep=",", fileEncoding = "latin1")
DivinationCard_lhc  = read.csv("./data/LHC.DivinationCard.csv", sep=",", fileEncoding = "latin1")
HelmetEnchant_lhc   = read.csv("./data/LHC.HelmetEnchant.csv", sep=",", fileEncoding = "latin1")
Resonator_lhc       = read.csv("./data/LHC.Resonator.csv", sep=",", fileEncoding = "latin1")
UniqueArmour_lhc    = read.csv("./data/LHC.UniqueArmour.csv", sep=",", fileEncoding = "latin1")
Incubator_lhc       = read.csv("./data/LHC.Incubator.csv", sep=",", fileEncoding = "latin1")
Watchstone_lhc      = read.csv("./data/LHC.Watchstone.csv", sep=",", fileEncoding = "latin1")

# SSC
BaseType_ssc        = read.csv("./data/SSC.BaseType.csv", sep=",", fileEncoding = "latin1")
BaseType_ssc$Date = as.Date(BaseType_ssc$Date)
Essence_ssc         = read.csv("./data/SSC.Essence.csv", sep=",", fileEncoding = "latin1")
Essence_ssc$Date = as.Date(Essence_ssc$Date)
Map_ssc             = read.csv("./data/SSC.Map.csv", sep=",", fileEncoding = "latin1")
Map_ssc$Date = as.Date(Map_ssc$Date)
Scarab_ssc          = read.csv("./data/SSC.Scarab.csv", sep=",", fileEncoding = "latin1")
Scarab_ssc$Date = as.Date(Scarab_ssc$Date)
UniqueFlask_ssc     = read.csv("./data/SSC.UniqueFlask.csv", sep=",", fileEncoding = "latin1")
UniqueFlask_ssc$Date = as.Date(UniqueFlask_ssc$Date)
UniqueWeapon_ssc    = read.csv("./data/SSC.UniqueWeapon.csv", sep=",", fileEncoding = "latin1")
UniqueWeapon_ssc$Date = as.Date(UniqueWeapon_ssc$Date)
Beast_ssc           = read.csv("./data/SSC.Beast.csv", sep=",", fileEncoding = "latin1")
Beast_ssc$Date = as.Date(Beast_ssc$Date)
Fossil_ssc          = read.csv("./data/SSC.Fossil.csv", sep=",", fileEncoding = "latin1")
Fossil_ssc$Date = as.Date(Fossil_ssc$Date)
Oil_ssc             = read.csv("./data/SSC.Oil.csv", sep=",", fileEncoding = "latin1")
Oil_ssc$Date = as.Date(Oil_ssc$Date)
SkillGem_ssc        = read.csv("./data/SSC.SkillGem.csv", sep=",", fileEncoding = "latin1")
SkillGem_ssc$Date = as.Date(SkillGem_ssc$Date)
Vial_ssc            = read.csv("./data/SSC.Vial.csv", sep=",", fileEncoding = "latin1")
Vial_ssc$Date = as.Date(Vial_ssc$Date)
UniqueJewel_ssc     = read.csv("./data/SSC.UniqueJewel.csv", sep=",", fileEncoding = "latin1")
UniqueJewel_ssc$Date = as.Date(UniqueJewel_ssc$Date)
Currency_ssc        = read.csv("./data/SSC.Currency.csv", sep=",", fileEncoding = "latin1")
Currency_ssc$Date = as.Date(Currency_ssc$Date)
Fragment_ssc        = read.csv("./data/SSC.Fragment.csv", sep=",", fileEncoding = "latin1")
Fragment_ssc$Date = as.Date(Fragment_ssc$Date)
Prophecy_ssc        = read.csv("./data/SSC.Prophecy.csv", sep=",", fileEncoding = "latin1")
Prophecy_ssc$Date = as.Date(Prophecy_ssc$Date)
UniqueAccessory_ssc = read.csv("./data/SSC.UniqueAccessory.csv", sep=",", fileEncoding = "latin1")
UniqueAccessory_ssc$Date = as.Date(UniqueAccessory_ssc$Date)
UniqueMap_ssc       = read.csv("./data/SSC.UniqueMap.csv", sep=",", fileEncoding = "latin1")
UniqueMap_ssc$Date = as.Date(UniqueMap_ssc$Date)
DivinationCard_ssc  = read.csv("./data/SSC.DivinationCard.csv", sep=",", fileEncoding = "latin1")
DivinationCard_ssc$Date = as.Date(DivinationCard_ssc$Date)
HelmetEnchant_ssc   = read.csv("./data/SSC.HelmetEnchant.csv", sep=",", fileEncoding = "latin1")
HelmetEnchant_ssc$Date = as.Date(HelmetEnchant_ssc$Date)
Resonator_ssc       = read.csv("./data/SSC.Resonator.csv", sep=",", fileEncoding = "latin1")
Resonator_ssc$Date = as.Date(Resonator_ssc$Date)
UniqueArmour_ssc    = read.csv("./data/SSC.UniqueArmour.csv", sep=",", fileEncoding = "latin1")
UniqueArmour_ssc$Date = as.Date(UniqueArmour_ssc$Date)
Incubator_ssc       = read.csv("./data/SSC.Incubator.csv", sep=",", fileEncoding = "latin1")
Incubator_ssc$Date = as.Date(Incubator_ssc$Date)
Watchstone_ssc      = read.csv("./data/SSC.Watchstone.csv", sep=",", fileEncoding = "latin1")
Watchstone_ssc$Date = as.Date(Watchstone_ssc$Date)
